version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: '3.12'
    nodejs: '22'
  jobs:
    post_install:
      - make install-frontend
    pre_build:
      - make frontend

python:
  install:
    - requirements: docs/requirements.txt
