version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
    nodejs: latest
  jobs:
    post_install:
      - make install-frontend
    pre_build:
      - make frontend

python:
  install:
    - requirements: docs/requirements.txt
