name: Publish to PyPI
on:
  release:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
    types: [released]
jobs:
  test:
    uses: ./.github/workflows/ci.yml

  build:
    needs: ['test']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Node dependencies
        run: |
          npm ci

      - name: Compile JavaScript
        run: |
          make frontend-dist

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: make setup-python

      - name: Build package distributions
        run: make build

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist

  # https://docs.pypi.org/trusted-publishers/using-a-publisher/
  pypi-publish:
    needs: ['build']
    environment: 'publish'

    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # Mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/download-artifact@v4

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: artifact/
          print-hash: true
